### PR TITLE
Week8 add api helper functions

### PR DESCRIPTION
**Pull request by treeebooor**
## Details 
Modified helper functions to use Rapid API. Also fixed most of the linting issues. I don't know how I should be exporting the variables and functions though.
## New Changes
- apiHelpers.js

## Checklist
- [x] I have requested 2+ code reviewers
- [x] I have reviewed and commented my own code.
- [x] My code follows the style guidelines of this project.
- [ ] I have added new tests as necessary.
- [ ] All new and existing tests pass successfully.

### CODE REVIEW

**Comment by hanran-y** [comment]
Is there any way to get data out of Promise other than this?
`getRecipesByName("rice", 5).then((result) => console.log(result));`
Output: `Array(5) [ {…}, {…}, {…}, {…}, {…} ]`

**Comment by treeebooor** [comment]
> Is there any way to get data out of Promise other than this? `getRecipesByName("rice", 5).then((result) => console.log(result));` Output: `Array(5) [ {…}, {…}, {…}, {…}, {…} ]`

Im not sure if there is an easier way because fetch is async so you have to wait for it to finish. Also these functions rely on the API key stored in a file called .env which i didn't upload to github. Lmk if you need it I can send it to you

**Comment by hanran-y** [comment]
> > Is there any way to get data out of Promise other than this? `getRecipesByName("rice", 5).then((result) => console.log(result));` Output: `Array(5) [ {…}, {…}, {…}, {…}, {…} ]`
> 
> Im not sure if there is an easier way because fetch is async so you have to wait for it to finish. Also these functions rely on the 

>API key stored in a file called .env which i didn't upload to github. Lmk if you need it I can send it to you

Oh, I used the key directly. Is that.env file contain the encrypted key? Or .env simply contain the key itself.

**Comment by treeebooor** [comment]
> Oh, I used the key directly. Is that.env file contain the encrypted key? Or .env simply contain the key itself.

Oh the code on the main branch is old.(so the branch you just created week9-api.. is old code) I changed it in this pull request to prevent exposing the API key.

**Comment by hanran-y** [comment]
> > Oh, I used the key directly. Is that.env file contain the encrypted key? Or .env simply contain the key itself.
> 
> Oh the code on the main branch is old.(so the branch you just created week9-api.. is old code) I changed it in this pull request to prevent exposing the API key.

Got you. Just deleted my test branche

**Pull request merged**
